# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BSBDJ' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BSBDJ

  target 'BSBDJTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BSBDJUITests' do
    inherit! :search_paths
    # Pods for testing
 end
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'SVProgressHUD', '~> 2.0.3'

end
